### ISSUE TITLE
Need to register turn runner

### ISSUE THREAD

**Issue by djberg96** [turn-project/turn#16]
I'd like to use turn as my global test runner (i.e. the runner I set in my global .test-unit.yml file), but it doesn't appear that turn registers itself as a runner via AutoRunner.register_runner.

**Comment by trans** [comment]
Is this a TestUnit 2.0+ feature?

**Comment by djberg96** [comment]
Oops, yes, test-unit 2. That ok?

**Comment by trans** [comment]
Unfortunately Turn doesn't specifically support TestUnit 2. The problem was TestUnit 2 has diverged from 1.0 and thus from MiniTest. The differences made it very difficult to support all three with the same code base. So in order to support MiniTest going forward it was decided that Turn's focus would need to be on Ruby's standard frameworks -- TestUnit 1.x for Ruby 1.8- and MiniTest for 1.9+.

Of course, we're open to code contributions.

**Comment by trans** [comment]
Turn 0.x series will not support Test::Unit 2. But next major series will (may skip to 2.x just to make it very clear). When that happens this issue will be resolved.
