### ISSUE TITLE
Turn has an unspecified dependency on MiniTest

### ISSUE THREAD

**Issue by wleeperogs** [turn-project/turn#59]
As of turn v. 0.8.3, there is an undocumented dependency on MiniTest. 

It appears this stems from some recent additions to support minitest.

I don't particularly care for all the extra output from MiniTest, so if this could be optional or sensing that would be the preferred fix.

**Comment by benatkin** [comment]
people are suggesting using 0.8.2 right now: http://stackoverflow.com/questions/7719114/rails-3-1-1-and-cucumber-error

**Comment by codeincontext** [comment]
+1 This gave a friend a fairly disappointing first time Rails experience. I blamed him for the problem, until I realised that turn had forgotten a dependency

**Comment by trans** [comment]
Technically this is because MiniTest is an _optional_ dependency since Turn can also be used with TestUnit library instead (1.x series). It would not normally be an issue, since MiniTest in included with Ruby. But the MiniTest shipped with Ruby is well behind the latest version of MiniTest, which Turn needs.

Since almost everyone has moved to MiniTest now, I will simply add it as a dependency.

Thanks for reporting.
