### ISSUE TITLE
turn 0.8.3 doesn't display time of individual tests

### ISSUE THREAD

**Issue by thoughtafter** [turn-project/turn#60]
One of the features I like about 0.8.2 is it displays the time of each individual test making it easy to locate long running tests and fix them.  I definitely prefer that turn 0.8.3 displays the test name before running the test, then follows it with pass/fail.  I would just ask that immediately after the pass/fail is the test time.  Thank you.

**Comment by trans** [comment]
I will consider this, thanks. In the mean time you might want to try the `pretty` format.

In test helper:

```
Turn.config.format = :pretty
```

or via command line

```
$ turn -T test/
```

**Comment by trans** [comment]
I added running time to default output. It is different from MiniTests way of doing things. It keeps a running clock of how long tests haven been running, rather than just the time it took to run a single test. This way you get more information, and you can still see how much time a single test took by subtracting it's time stamp form the last test's.
