### ISSUE TITLE
with 0.8.3, turn --version reports 0.9.0

### ISSUE THREAD

**Issue by aspiers** [turn-project/turn#65]
I have turn 0.8.3 installed, but `turn --version` outputs `0.9.0`.  Here is [the guilty commit](https://github.com/TwP/turn/commit/8547ffe3197cabfd03066748e7b67f222f4f6b89#diff-10) made back in August, before 0.8.3 was released - presumably someone changed their mind about what the next version number would be, and forgot to fix this.

**Comment by trans** [comment]
You are correct, sir. I did indeed pull back from a 0.9.0 release to get a release out sooner rather than later, and overlooked this. I guess there's nothing to be done about it now. 0.9.0 will be out shortly and no doubt 0.9.1 quickly there after (there's almost always something that needs fixing in a .0 release). At that point I'll yank 0.8.3 since it had a couple of issues, and we should be okay.

Let me know if you have alternate/better advice on how to handle.

Thanks.

**Comment by trans** [comment]
I am going to go ahead and close this. Like I said, issue will essentially be resolved with the next release. Thanks again.
