### ISSUE TITLE
Turn eats useful backtrace when custom assertions are used

### ISSUE THREAD

**Issue by madadam** [turn-project/turn#7]
When I use custom assertions, I only see the backtrace point to the place where the the assertion is defined, not where it is used. Simple example is here: http://gist.github.com/256065

When I run it, I see this: http://gist.github.com/256066

So the backtrace part pointing to where the assertion is called is missing. This makes it very difficult to track the source of the failure, especially when there is lot of tests.

**Comment by TwP** [comment]
The output is correct. The assertion is failng on the "assert_equal" line. The Test::Unit framework reports the location of this line number since that is the only one it knows about. The turn gem does not have access to the stack trace when it's output is generated.

Instead of using assert_equal, you should use assert_block ...

http://ruby-doc.org/stdlib/libdoc/test/unit/rdoc/classes/Test/Unit/Assertions.html#M004505

**Comment by madadam** [comment]
Ok, but if I use just plain test/unit, the output contains full backtrace (http://gist.github.com/256202). Is there some kind of backtrace suppressing going on? If yes, then it does not work as expected in this case.

On the other hand, thanks for the `assert_block` tip. Will give it a shot.
