### ISSUE TITLE
TestRunners cases didn't pass

### ISSUE THREAD

**Issue by y8** [turn-project/turn#75]
@trans, you defo should take a look at falling tests before release.

**Comment by trans** [comment]
What didn't pass? I aways make sure tests are green before release (at least on my system).

**Comment by trans** [comment]
You mean before I push. Yea, I probably should get in the habit of working in a branch instead of master and getting green before merging to master. I'll make an effort to do that in the future.

Anyway, it was pretty simple fixes, and except for one case it was the tests that needed adjustment not lib code. Fixed now.
