### ISSUE TITLE
line number of offending test not output

### ISSUE THREAD

**Issue by ExistsAndIs1** [turn-project/turn#80]
```test_find_matching                                                   FAIL
        Failed assertion, no message given.
        Assertion at /home/stefan/.rvm/gems/ruby-1.9.3-rc1@sharewise/gems/activesupport-3.1.1/lib/active_support/testing/setup_and_teardown.rb:35:in`block in run'

```
vs. without turn
```

  1) Failure:
test_find_matching(PromotionTest) [test/unit/promotion_test.rb:22]:
Failed assertion, no message given.

```
with turn enabled i have no idea which line in the tests caused the issue
without turn I see its line 22 in my test
```

**Comment by trans** [comment]
The latest updates probably already address this. I will be releasing soon.

**Comment by leifg** [comment]
It's fixed in 0.9.4. But is it possible to backport this fix to 0.8 version as we cannot use the latest version.

**Comment by trans** [comment]
Oh? Why can't you use latest version?

**Comment by leifg** [comment]
Because I'm not using Minitest and there seems to be some problems with Rails 2.3 and Ruby 1.8.7 anyway: https://github.com/TwP/turn/issues/90

**Comment by trans** [comment]
I see. So you are using Test::Unit rather then Minitest. Is that right? If so, here are two possible solutions:

1) You can use MiniTest even on 1.8.7. Just install `minitest` gem and run tests via it instead. Unless you have used highly specific Test::Unit code it should be able to run your TestUnit tests just fine.

2) If, on the other hand, you are a Test::Unit shop (so to speak) using Test::Unit 2.x, the better solution is to use [Tapout](http://github.com/rubyworks/tapout) instead of Turn along with the [test-unit-runner-tap](https://github.com/test-unit/test-unit-runner-tap) plugin.

The reason for these solutions is b/c, as of 0.9.x, Turn is MiniTest only. This was done for a few reasons. In particular b/c it was very difficult to support two diverging frameworks. So it was decided to focus Turn on supporting just what framework Ruby supports out of the box, and to create Tapout as the future of test reporting for all others.

**Comment by leifg** [comment]
Thanks for the advice.

The switch to MiniTest is not possible because most of the tests we wrote don't use the Test::Unit::TestCase as a base class but the ActiveSupport::TestCase base class (which then depends on Test::Unit::TestCase).

I looked in the test-unit-runner-tap plugin but it seems that there is also a problem with executing tests (see https://github.com/test-unit/test-unit-runner-tap/issues/3)

**Comment by trans** [comment]
BTW, don't know if it matters now, but... in working on the test-unit-runner-tap issue, I noticed ActiveSupport 2.3.14 seems to have support for MiniTest.

See https://github.com/rails/rails/blob/2-3-stable/activesupport/lib/active_support/test_case.rb

**Comment by trans** [comment]
I am assuming this has been taken care of by using the [test-unit-rails](https://github.com/test-unit/test-unit-rails) plugin. Please reopen or submit new issue if this has not addressed the issue.
